import { createClient } from '@/utils/supabase/server';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { DIM_KEYS, DIM_NAMES, topShifts } from '@/lib/dimensions';
import { getServerLocale } from '@/lib/locale-server';
import { t } from '@/lib/translations';
import LanguageSwitcher from '@/components/language-switcher';
import MullWordmark from '@/components/mull-wordmark';
import type { Metadata } from 'next';

const serif = "'Cormorant Garamond', Georgia, serif";
const sans = "'Inter', system-ui, sans-serif";
const pixel = "var(--font-pixel-display, 'Courier New', monospace)";

type ProfileRow = {
  user_id: string;
  handle: string;
  display_name: string | null;
  bio: string | null;
  show_archetype: boolean;
  show_dimensions: boolean;
  show_map: boolean;
  show_streak: boolean;
};

type Attempt = {
  archetype: string;
  flavor: string | null;
  alignment_pct: number;
  taken_at: string;
  vector: number[];
};

type DilemmaRow = {
  id: string;
  dilemma_date: string;
  question_text: string;
  response_text: string;
  vector_delta: number[] | null;
  analysis: string | null;
  created_at: string;
};
type DiaryRow = {
  id: string;
  title: string | null;
  content: string;
  vector_delta: number[] | null;
  analysis: string | null;
  word_count: number | null;
  created_at: string;
};

function vecAdd(a: number[], b: number[]): number[] {
  return a.map((v, i) => v + (b[i] || 0));
}

// Generate per-profile share-preview metadata. Renders nicely on Twitter,
// Slack, iMessage, etc. Falls back to generic Mull description when the
// profile is missing or has chosen a low-disclosure setup.
export async function generateMetadata({ params }: { params: Promise<{ handle: string }> }): Promise<Metadata> {
  const { handle } = await params;
  const supabase = await createClient();
  const { data: profile } = await supabase
    .from('public_profiles')
    .select('user_id, handle, display_name, bio, show_archetype')
    .eq('handle', handle.toLowerCase())
    .maybeSingle<{ user_id: string; handle: string; display_name: string | null; bio: string | null; show_archetype: boolean }>();
  if (!profile) {
    return { title: 'Not found', description: 'No public profile at this handle.' };
  }
  const name = profile.display_name || profile.handle;
  let description = profile.bio || '';
  if (!description && profile.show_archetype) {
    const { data: latest } = await supabase
      .rpc('get_public_latest_archetype', { p_user_id: profile.user_id });
    const arch = (latest?.[0]?.archetype as string | undefined);
    const flavor = (latest?.[0]?.flavor as string | undefined);
    if (arch) description = `${flavor ? flavor + ' ' : ''}${arch} on Mull — find your place on the map of how you think.`;
  }
  if (!description) description = `${name} on Mull — find your place on the map of how you think.`;
  const title = `${name} on Mull`;
  const url = `https://mull.world/u/${profile.handle}`;
  // Generated by app/u/[handle]/opengraph-image.tsx — personalized card
  // showing the user's display name + (privacy-respecting) archetype.
  const ogImage = `${url}/opengraph-image`;
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: 'Mull',
      type: 'profile',
      images: [{ url: ogImage, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
    alternates: { canonical: url },
  };
}

export default async function PublicProfilePage({ params }: { params: Promise<{ handle: string }> }) {
  const { handle } = await params;
  const supabase = await createClient();
  const locale = await getServerLocale();

  const { data: profile } = await supabase
    .from('public_profiles')
    .select('user_id, handle, display_name, bio, show_archetype, show_dimensions, show_map, show_streak')
    .eq('handle', handle.toLowerCase())
    .maybeSingle<ProfileRow>();

  if (!profile) notFound();

  // Trajectory and latest archetype come from SECURITY DEFINER functions that
  // expose only vectors/timestamps (no prose) and only when the user has a
  // public profile. Per-entry text is read separately via the public is_public
  // RLS policy on dilemma_responses + diary_entries.
  const [trajRes, latestArchRes, publicDilemmasRes, publicDiariesRes] = await Promise.all([
    supabase.rpc('get_public_trajectory', { p_user_id: profile.user_id }),
    supabase.rpc('get_public_latest_archetype', { p_user_id: profile.user_id }),
    supabase
      .from('dilemma_responses')
      .select('id, dilemma_date, question_text, response_text, vector_delta, analysis, created_at')
      .eq('user_id', profile.user_id)
      .eq('is_public', true)
      .order('created_at', { ascending: false })
      .limit(5)
      .returns<DilemmaRow[]>(),
    supabase
      .from('diary_entries')
      .select('id, title, content, vector_delta, analysis, word_count, created_at')
      .eq('user_id', profile.user_id)
      .eq('is_public', true)
      .order('created_at', { ascending: false })
      .limit(5)
      .returns<DiaryRow[]>(),
  ]);

  type TrajRow = { kind: 'q' | 'd' | 'j' | 'e'; ts: string; dilemma_date: string | null; vec: number[] | null; delta: number[] | null };
  const trajRows = (trajRes.data ?? []) as TrajRow[];
  const latestArch = (latestArchRes.data?.[0] ?? null) as Attempt | null;
  const publicDilemmas = publicDilemmasRes.data ?? [];
  const publicDiaries = publicDiariesRes.data ?? [];

  // Build chronological event list (oldest → newest) for trajectory
  const events = trajRows.map(r => ({
    kind: r.kind,
    ts: new Date(r.ts).getTime(),
    vec: r.vec,
    delta: r.delta,
    dilemma_date: r.dilemma_date,
  })).sort((a, b) => a.ts - b.ts);

  // Walk events, accumulating position; collect positions for trail
  const trailPositions: number[][] = [];
  let position: number[] = new Array(16).fill(0);
  for (const ev of events) {
    if (ev.kind === 'q' && Array.isArray(ev.vec) && ev.vec.length === 16) {
      position = ev.vec.slice();
    } else if (Array.isArray(ev.delta) && ev.delta.length === 16) {
      position = vecAdd(position, ev.delta);
    }
    trailPositions.push(position.slice());
  }
  const trailVectors = trailPositions.slice(-10);

  // Streak with one-day grace — single missed day forgiven.
  function computeStreak(dates: string[]): number {
    if (!dates.length) return 0;
    const set = new Set(dates);
    const today = new Date(); today.setUTCHours(0, 0, 0, 0);
    const cursor = new Date(today);
    if (!set.has(cursor.toISOString().slice(0, 10))) {
      cursor.setUTCDate(cursor.getUTCDate() - 1);
    }
    let streak = 0;
    let graceUsed = false;
    for (let i = 0; i < 1825; i++) {
      const k = cursor.toISOString().slice(0, 10);
      if (set.has(k)) {
        streak++;
        cursor.setUTCDate(cursor.getUTCDate() - 1);
      } else if (!graceUsed) {
        graceUsed = true;
        cursor.setUTCDate(cursor.getUTCDate() - 1);
      } else {
        break;
      }
    }
    return streak;
  }
  const dilemmaDates = events.filter(e => e.kind === 'd' && e.dilemma_date).map(e => e.dilemma_date as string);
  const streak = computeStreak(dilemmaDates);
  const latest = latestArch;

  const topDims = position
    .map((v, i) => ({ key: DIM_KEYS[i], name: DIM_NAMES[DIM_KEYS[i]], v }))
    .sort((a, b) => b.v - a.v)
    .slice(0, 5);

  const hasMapData = profile.show_map && position.some(v => v !== 0);
  const encodedVec = hasMapData
    ? encodeURIComponent(Buffer.from(JSON.stringify(position)).toString('base64'))
    : null;
  const encodedHist = hasMapData && trailVectors.length > 1
    ? encodeURIComponent(Buffer.from(JSON.stringify(trailVectors)).toString('base64'))
    : null;
  const iframeSrc = encodedVec
    ? `/?embed=map&v=${encodedVec}${encodedHist ? `&h=${encodedHist}` : ''}`
    : null;

  const headline = profile.show_archetype && latest
    ? `${latest.flavor ? latest.flavor + ' ' : ''}${latest.archetype.replace(/^The /, '')}`
    : t('pub.anonymous_mind', locale);

  const displayName = profile.display_name || profile.handle;

  const fmtDate = (s: string) =>
    new Date(s).toLocaleDateString(locale === 'en' ? 'en-GB' : locale, { day: 'numeric', month: 'short', year: 'numeric' });

  return (
    <main style={{ maxWidth: 760, margin: '0 auto', padding: '60px 24px 100px' }}>
      <header style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginBottom: 36,
        gap: 16,
        flexWrap: 'wrap',
      }}>
        <MullWordmark />
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <LanguageSwitcher initial={locale} />
          {/* Compare CTA — chunky amber pixel chip. The single most
              interesting CTA on someone else's profile shouldn't read
              like a tiny underline in the corner. */}
          <Link
            href={`/compare?them=${profile.handle}`}
            className="pixel-press"
            style={{
              display: 'inline-block',
              padding: '8px 14px',
              background: '#B8862F',
              color: '#1A1612',
              border: '3px solid #221E18',
              boxShadow: '3px 3px 0 0 #221E18',
              borderRadius: 0,
              fontFamily: pixel,
              fontSize: 11,
              letterSpacing: 0.4,
              textDecoration: 'none',
              textTransform: 'uppercase',
              transition: 'transform 80ms steps(2, end), box-shadow 80ms steps(2, end)',
            }}
          >
            ▸ COMPARE WITH ME
          </Link>
          <Link href="/" style={{
            fontFamily: pixel, fontSize: 11, color: '#4A4338',
            textDecoration: 'none', letterSpacing: 0.4,
            textTransform: 'uppercase',
          }}>
            {t('nav.find_your_place', locale).toUpperCase()}
          </Link>
        </div>
      </header>

      {/* Pixel handle eyebrow → big serif display name. Two layers of
          chrome: the eyebrow caret + the name itself. */}
      <div style={{
        fontFamily: pixel,
        fontSize: 12,
        color: '#8C6520',
        textTransform: 'uppercase',
        letterSpacing: '0.18em',
        marginBottom: 14,
      }}>
        ▸ @{profile.handle}
      </div>

      <h1 style={{
        fontFamily: serif,
        fontSize: 44,
        fontWeight: 500,
        margin: '0 0 8px',
        letterSpacing: '-0.01em',
        lineHeight: 1.1,
      }}>
        {displayName}
      </h1>

      {profile.show_archetype && latest && (
        <p style={{
          fontFamily: serif,
          fontStyle: 'italic',
          fontSize: 22,
          color: '#8C6520',
          margin: '0 0 18px',
        }}>
          {headline}
          {' · '}
          <span style={{
            fontFamily: pixel,
            fontStyle: 'normal',
            fontSize: 13,
            color: '#8C6520',
            letterSpacing: 0.4,
          }}>
            {latest.alignment_pct}{t('account.percent_alignment', locale).toUpperCase()}
          </span>
        </p>
      )}

      {profile.bio && (
        <p style={{
          fontFamily: serif,
          fontSize: 18,
          color: '#221E18',
          margin: '0 0 32px',
          lineHeight: 1.55,
          maxWidth: 560,
        }}>
          {profile.bio}
        </p>
      )}

      {/* Public-profile stat row — matches /account stat-card style.
          Promotes the streak from a tiny chip into a proper "this
          person actually does this" signal. Three columns when full;
          collapses to whichever cards have signal. */}
      {((profile.show_streak && streak > 0) || publicDilemmas.length > 0 || publicDiaries.length > 0) && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: 14,
          marginBottom: 36,
        }}>
          {profile.show_streak && streak > 0 && (
            <div style={{
              padding: '16px 20px',
              background: '#221E18',
              border: '4px solid #221E18',
              boxShadow: '4px 4px 0 0 #B8862F',
              borderRadius: 0,
              color: '#FAF6EC',
            }}>
              <div style={{
                fontFamily: pixel, fontSize: 28,
                color: '#F8EDC8', lineHeight: 1, letterSpacing: 0.4,
              }}>
                {streak >= 30 ? '30+' : streak}
                <span style={{ fontSize: 13, opacity: 0.7, marginLeft: 6 }}>
                  {streak === 1 ? 'DAY' : 'DAYS'}
                </span>
              </div>
              <div style={{
                fontFamily: pixel, fontSize: 10,
                color: '#F1C76A', textTransform: 'uppercase',
                letterSpacing: '0.18em', marginTop: 8,
              }}>
                STREAK{streak >= 30 ? ` · ${streak} DAYS` : ''}
              </div>
            </div>
          )}
          {publicDilemmas.length > 0 && (
            <div style={{
              padding: '16px 20px',
              background: '#FFFCF4',
              border: '4px solid #221E18',
              boxShadow: '4px 4px 0 0 #3D7DA8',
              borderRadius: 0,
            }}>
              <div style={{
                fontFamily: pixel, fontSize: 28,
                color: '#221E18', lineHeight: 1, letterSpacing: 0.4,
              }}>{publicDilemmas.length}</div>
              <div style={{
                fontFamily: pixel, fontSize: 10,
                color: '#3D7DA8', textTransform: 'uppercase',
                letterSpacing: '0.18em', marginTop: 8,
              }}>
                {publicDilemmas.length === 1 ? 'PUBLIC DILEMMA' : 'PUBLIC DILEMMAS'}
              </div>
            </div>
          )}
          {publicDiaries.length > 0 && (
            <div style={{
              padding: '16px 20px',
              background: '#FFFCF4',
              border: '4px solid #221E18',
              boxShadow: '4px 4px 0 0 #2F5D5C',
              borderRadius: 0,
            }}>
              <div style={{
                fontFamily: pixel, fontSize: 28,
                color: '#221E18', lineHeight: 1, letterSpacing: 0.4,
              }}>{publicDiaries.length}</div>
              <div style={{
                fontFamily: pixel, fontSize: 10,
                color: '#2F5D5C', textTransform: 'uppercase',
                letterSpacing: '0.18em', marginTop: 8,
              }}>
                {publicDiaries.length === 1 ? 'PUBLIC DIARY' : 'PUBLIC DIARIES'}
              </div>
            </div>
          )}
        </div>
      )}

      {iframeSrc && (
        <section style={{ marginBottom: 44 }}>
          <h2 style={pixelSectionH2('#2F5D5C')}>
            ▸ {t('pub.their_place', locale).toUpperCase()}
          </h2>
          <div style={{
            border: '4px solid #221E18',
            boxShadow: '5px 5px 0 0 #2F5D5C',
            borderRadius: 0,
            overflow: 'hidden',
            background: '#FFFCF4',
          }}>
            <iframe
              src={iframeSrc}
              style={{
                width: '100%',
                height: 480,
                border: 'none',
                display: 'block',
              }}
              title={`${displayName}'s position on the philosophical map`}
              loading="lazy"
            />
          </div>
          {trailVectors.length > 1 && (
            <p style={{
              fontFamily: pixel,
              fontSize: 11,
              color: '#8C6520',
              marginTop: 12,
              opacity: 0.85,
              letterSpacing: 0.4,
              textTransform: 'uppercase',
            }}>
              {t('pub.trail_caption', locale, { count: trailVectors.length }).toUpperCase()}
            </p>
          )}
        </section>
      )}

      {profile.show_dimensions && topDims.some(d => d.v > 0) && (
        <section style={{ marginBottom: 44 }}>
          <h2 style={pixelSectionH2('#B8862F')}>
            ▸ {t('pub.strongest_tendencies', locale).toUpperCase()}
          </h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 12 }}>
            {topDims.map(d => (
              // Switched from a fixed 180px / 1fr / 50px grid to a
              // flex-wrap layout: on wide screens the name + bar +
              // value sit on one row; on phones (~320px viewport)
              // the name wraps to its own line above a full-width
              // bar, instead of being crushed into a 30px-wide bar.
              <li key={d.key} style={{
                display: 'flex',
                flexWrap: 'wrap',
                gap: 14,
                alignItems: 'center',
                fontFamily: serif,
                fontSize: 15,
                color: '#221E18',
              }}>
                <span style={{ minWidth: 140 }}>{d.name}</span>
                <div style={{
                  height: 10,
                  background: '#FAF6EC',
                  border: '2px solid #221E18',
                  borderRadius: 0,
                  overflow: 'hidden',
                  flex: 1,
                  minWidth: 120,
                }}>
                  <div style={{
                    height: '100%',
                    width: `${Math.max(0, Math.min(100, (d.v / 12) * 100))}%`,
                    background: '#B8862F',
                    transition: 'width 0.4s steps(8, end)',
                  }} />
                </div>
                <span style={{
                  fontFamily: pixel,
                  fontSize: 13,
                  fontVariantNumeric: 'tabular-nums',
                  color: '#8C6520',
                  textAlign: 'right',
                  minWidth: 50,
                  letterSpacing: 0.4,
                }}>
                  {d.v.toFixed(1)}
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {publicDilemmas.length > 0 && (
        <section style={{ marginBottom: 44 }}>
          <h2 style={pixelSectionH2('#3D7DA8')}>
            ▸ RECENT DILEMMA RESPONSES · LAST {publicDilemmas.length}
          </h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 14 }}>
            {publicDilemmas.map(d => {
              const shifts = topShifts(d.vector_delta || [], 0.3, 3);
              return (
                <li key={d.id} style={publicEntryCard('#3D7DA8')}>
                  <div style={publicEventEyebrow('#3D7DA8')}>
                    DAILY DILEMMA · {fmtDate(d.created_at).toUpperCase()}
                  </div>
                  <p style={{
                    fontFamily: serif,
                    fontStyle: 'italic',
                    fontSize: 16,
                    color: '#4A4338',
                    margin: '0 0 8px',
                  }}>
                    &ldquo;{d.question_text}&rdquo;
                  </p>
                  <p style={{
                    fontFamily: serif,
                    fontSize: 16,
                    color: '#221E18',
                    margin: '0 0 8px',
                    lineHeight: 1.55,
                    whiteSpace: 'pre-wrap',
                  }}>
                    {d.response_text}
                  </p>
                  {d.analysis && (
                    <p style={publicEventAnalysis}>
                      {d.analysis}
                    </p>
                  )}
                  {shifts.length > 0 && (
                    <div style={publicShiftsRow}>
                      {shifts.map(s => (
                        <span key={s.key} style={publicShiftChip(s.delta > 0)}>
                          <strong style={{ fontVariantNumeric: 'tabular-nums' }}>
                            {s.delta > 0 ? '+' : ''}{s.delta.toFixed(1)}
                          </strong>{' '}
                          {s.name}
                        </span>
                      ))}
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        </section>
      )}

      {publicDiaries.length > 0 && (
        <section style={{ marginBottom: 44 }}>
          <h2 style={pixelSectionH2('#2F5D5C')}>
            ▸ RECENT DIARY ENTRIES · LAST {publicDiaries.length}
          </h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 14 }}>
            {publicDiaries.map(d => {
              const shifts = topShifts(d.vector_delta || [], 0.3, 3);
              const preview = d.content.length > 320 ? d.content.slice(0, 320) + '…' : d.content;
              return (
                <li key={d.id} style={publicEntryCard('#2F5D5C')}>
                  <div style={publicEventEyebrow('#2F5D5C')}>
                    DIARY ENTRY · {fmtDate(d.created_at).toUpperCase()}
                  </div>
                  {d.title && (
                    <div style={{
                      fontFamily: serif,
                      fontSize: 19,
                      fontWeight: 500,
                      color: '#221E18',
                      marginBottom: 6,
                    }}>
                      {d.title}
                    </div>
                  )}
                  <p style={{
                    fontFamily: serif,
                    fontSize: 16,
                    color: '#221E18',
                    margin: '0 0 8px',
                    lineHeight: 1.55,
                    whiteSpace: 'pre-wrap',
                  }}>
                    {preview}
                  </p>
                  {d.analysis && (
                    <p style={publicEventAnalysis}>
                      {d.analysis}
                    </p>
                  )}
                  {shifts.length > 0 && (
                    <div style={publicShiftsRow}>
                      {shifts.map(s => (
                        <span key={s.key} style={publicShiftChip(s.delta > 0)}>
                          <strong style={{ fontVariantNumeric: 'tabular-nums' }}>
                            {s.delta > 0 ? '+' : ''}{s.delta.toFixed(1)}
                          </strong>{' '}
                          {s.name}
                        </span>
                      ))}
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        </section>
      )}

      {/* Bottom CTA — pixel cream-on-amber dialog window. The whole
          dialog is now a Link (was: dialog with a small text-link
          inside). The arc-shape ends here for unauthed visitors:
          take the quiz. */}
      <Link
        href="/"
        className="pixel-press pixel-press--lg"
        style={{
          display: 'block',
          marginTop: 56,
          padding: '20px 24px',
          background: '#F8EDC8',
          border: '4px solid #221E18',
          boxShadow: '5px 5px 0 0 #B8862F',
          borderRadius: 0,
          fontFamily: serif,
          fontSize: 15,
          color: '#221E18',
          lineHeight: 1.55,
          textDecoration: 'none',
          transition: 'transform 80ms steps(2, end), box-shadow 80ms steps(2, end)',
        }}
      >
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 16,
          flexWrap: 'wrap',
        }}>
          <span>
            <strong style={{ color: '#221E18' }}>{t('pub.cta_title', locale)}</strong>{' '}
            {t('pub.cta_body', locale)}
          </span>
          <span style={{
            color: '#1A1612',
            background: '#B8862F',
            padding: '8px 14px',
            border: '3px solid #221E18',
            boxShadow: '3px 3px 0 0 #221E18',
            fontFamily: pixel,
            fontSize: 11,
            letterSpacing: 0.4,
            textTransform: 'uppercase',
            flexShrink: 0,
          }}>
            ▸ {t('pub.cta_link', locale).toUpperCase()}
          </span>
        </div>
      </Link>
    </main>
  );
}

// Pixel section heading: caret + uppercase pixel display + accent
// drop shadow. Used for each major section on /u/[handle].
function pixelSectionH2(accent: string): React.CSSProperties {
  return {
    fontFamily: pixel,
    fontSize: 16,
    color: '#221E18',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    margin: '0 0 16px',
    textShadow: `2px 2px 0 ${accent}`,
  };
}

// One public entry card (dilemma response or diary entry) — chunky
// pixel chrome, accent-colored hard shadow that matches the section.
function publicEntryCard(accent: string): React.CSSProperties {
  return {
    padding: '18px 22px',
    background: '#FFFCF4',
    border: '4px solid #221E18',
    boxShadow: `4px 4px 0 0 ${accent}`,
    borderRadius: 0,
  };
}

function publicEventEyebrow(accent: string): React.CSSProperties {
  return {
    fontFamily: pixel,
    fontSize: 11,
    color: accent,
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    marginBottom: 10,
  };
}

const publicEventAnalysis: React.CSSProperties = {
  fontFamily: serif,
  fontStyle: 'italic',
  fontSize: 14,
  color: '#8C6520',
  margin: '0 0 8px',
  lineHeight: 1.5,
};

const publicShiftsRow: React.CSSProperties = {
  display: 'flex',
  gap: 10,
  flexWrap: 'wrap',
  marginTop: 12,
  paddingTop: 12,
  borderTop: '2px dashed #D6CDB6',
};

function publicShiftChip(positive: boolean): React.CSSProperties {
  return {
    fontFamily: pixel,
    fontSize: 11,
    color: positive ? '#2F5D5C' : '#7A2E2E',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    padding: '4px 10px',
    background: positive ? '#E5F0EE' : '#F5E0E0',
    border: `2px solid ${positive ? '#2F5D5C' : '#7A2E2E'}`,
  };
}
