import Link from 'next/link';
import { PHILOSOPHERS } from '@/lib/philosophers';
import { createClient } from '@/utils/supabase/server';
import DebateForm from './debate-form';

const serif = "'Cormorant Garamond', Georgia, serif";
const sans = "'Inter', system-ui, sans-serif";

type SavedDebate = {
  id: string;
  a_name: string;
  a_dates: string | null;
  a_archetype_key: string | null;
  b_name: string;
  b_dates: string | null;
  b_archetype_key: string | null;
  topic: string;
  setup: string | null;
  exchanges: { speaker: 'A' | 'B'; text: string }[];
  created_at: string;
};

export default async function DebatePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let savedDebates: SavedDebate[] = [];
  if (user) {
    const { data } = await supabase
      .from('debate_history')
      .select('id, a_name, a_dates, a_archetype_key, b_name, b_dates, b_archetype_key, topic, setup, exchanges, created_at')
      .order('created_at', { ascending: false })
      .limit(3)
      .returns<SavedDebate[]>();
    savedDebates = data ?? [];
  }

  return (
    <main style={{ maxWidth: 820, margin: '0 auto', padding: '60px 24px 120px' }}>
      <header style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginBottom: 36,
        gap: 16,
        flexWrap: 'wrap',
      }}>
        <Link href="/" style={{
          fontFamily: serif,
          fontSize: 28,
          fontWeight: 500,
          color: '#221E18',
          textDecoration: 'none',
          letterSpacing: '-0.5px'
        }}>
          Mull<span style={{ color: '#B8862F' }}>.</span>
        </Link>
        <nav style={{ display: 'flex', gap: 18 }}>
          <Link href="/dilemma" style={{ fontFamily: sans, fontSize: 13, color: '#4A4338', textDecoration: 'none' }}>
            Today's dilemma →
          </Link>
          <Link href="/account" style={{ fontFamily: sans, fontSize: 13, color: '#4A4338', textDecoration: 'none' }}>
            Your account →
          </Link>
        </nav>
      </header>

      <div style={{
        fontFamily: sans,
        fontSize: 11,
        fontWeight: 600,
        color: '#8C6520',
        textTransform: 'uppercase',
        letterSpacing: '0.18em',
        marginBottom: 14,
      }}>
        Simulated debate · two thinkers, one topic
      </div>
      <h1 style={{
        fontFamily: serif,
        fontSize: 44,
        fontWeight: 500,
        margin: '0 0 12px',
        letterSpacing: '-0.01em',
        lineHeight: 1.05,
      }}>
        A <em style={{ color: '#8C6520' }}>simulated</em> exchange between any two thinkers in the constellation.
      </h1>
      <p style={{
        fontFamily: serif,
        fontStyle: 'italic',
        fontSize: 18,
        color: '#4A4338',
        marginBottom: 12,
        lineHeight: 1.5,
      }}>
        Pick two philosophers, give them a topic, and watch them argue in their own recorded positions. Useful for testing a tension, sharpening your own view, or seeing how voices across centuries would meet on a question.
      </p>
      <p style={{
        fontFamily: sans,
        fontSize: 12.5,
        color: '#8C6520',
        marginBottom: 36,
        opacity: 0.85,
        lineHeight: 1.55,
      }}>
        These exchanges are simulated by Claude from each thinker's recorded positions. Useful for thinking with — not for citation.{user && ' Your most recent three debates are saved below.'}
      </p>

      <DebateForm philosophers={PHILOSOPHERS} savedDebates={savedDebates} />

      <p style={{
        fontFamily: sans,
        fontSize: 12,
        color: '#8C6520',
        marginTop: 48,
        opacity: 0.75,
        textAlign: 'center',
        letterSpacing: 0.3,
        lineHeight: 1.55,
      }}>
        Generated by Claude from each thinker's recorded positions. The exchange is a sketch, not a transcript — useful for thinking with, not citation.
      </p>
    </main>
  );
}
