// Translations of the 16-dimension narration fragments in
// lib/dim-narration.ts (DIM_NARRATIONS), keyed by dim key → locale →
// { label, high, low }. Used by /compare to render each user's stance
// on the dimensions where they most diverge / converge.
//
// The English source builds its sentences by splicing a degree qualifier
// ("strongly", "moderately", "just barely") *after* the leading English
// verb of each fragment — grammar that doesn't carry to other languages.
// So for non-English locales poleSentence() switches to a simpler
// prefix template: qualifier + fragment. The fragments here are therefore
// translated as standalone verb-phrases that read naturally with a
// prefixed adverb (zh: "强烈地" + "认为苦难是根本的").
//
// The DIM_NARRATION_I18N block between the sentinels is GENERATED by
// scripts/translate-content.mjs — don't hand-edit inside them. The type,
// the qualifier table, and the getLocalizedDimNarration helper below are
// hand-maintained. English is the source (lives in DIM_NARRATIONS), so a
// missing locale/field falls back to English at the call site.

import type { Locale } from './translations';

export type DimNarrationI18nFields = {
  /** Translated short label (mirrors DIM_NARRATIONS[k].label). */
  label?: string;
  /** Translated high-pole verb-phrase. */
  high?: string;
  /** Translated low-pole verb-phrase. */
  low?: string;
};

// ─── BEGIN gen-translate DIM_NARRATION_I18N ───
export const DIM_NARRATION_I18N: Record<string, Partial<Record<Locale, DimNarrationI18nFields>>> = {
  "TV": {
    "zh": {
      "label": "悲剧性视野",
      "high": "视苦难为存在的根本——意义在于你如何直面它",
      "low": "视人生为基本可为之事，苦难不过是有待解决的问题"
    }
  },
  "VA": {
    "zh": {
      "label": "对生命的肯定",
      "high": "肯定生命本来的样子——快乐与存在本身无需外在的证明",
      "low": "视当下的生命为某种更高之物的准备或衬托"
    }
  },
  "WP": {
    "zh": {
      "label": "塑造意志",
      "high": "塑造世界而非顺受——价值源于努力与精通",
      "low": "重视顺受与接纳，胜于主动求变"
    }
  },
  "TR": {
    "zh": {
      "label": "对理性的信赖",
      "high": "信赖从清晰原则出发的审慎推理——视之为通达真理的最可靠途径",
      "low": "对纯粹演绎推理持审慎态度——尤其当其脱离经验而悬空运转时"
    }
  },
  "TE": {
    "zh": {
      "label": "对经验的信赖",
      "high": "信赖可观察、可检验、可证实之物——以经验为先",
      "low": "认为最要紧的事物皆在可量度之域的彼端"
    }
  },
  "RT": {
    "zh": {
      "label": "对传统的敬重",
      "high": "重视世代相传的智慧，视之为真实的资源——传统已以自身的分量赢得尊重",
      "low": "警惕承袭而来的思想框架——其中大多数早已到了需要重新审视的时候"
    }
  },
  "MR": {
    "zh": {
      "label": "神秘感受力",
      "high": "开放于言语所不能抵达之处——事物的表面并非全部",
      "low": "怀疑一切神秘主义的主张——凡无法清晰言说的，或许根本不真实"
    }
  },
  "SR": {
    "zh": {
      "label": "怀疑本能",
      "high": "要求先见证据方肯接受主张——非凡的断言，需要非凡的证明",
      "low": "接受内心感到真实的事物，即便缺乏明确的论证依据"
    }
  },
  "CE": {
    "zh": {
      "label": "共同体根植性",
      "high": "扎根于共同体——你之为你，大半由先人所赐予",
      "low": "倾向于个人主义——意义是每个人为自身所独自建构的"
    }
  },
  "SS": {
    "zh": {
      "label": "自我主权",
      "high": "信任自身的判断，而非随众——以主权之姿对抗因循的成见",
      "low": "重视集体的智慧，胜于一己的确信——众人往往知晓你所未知之事"
    }
  },
  "PO": {
    "zh": {
      "label": "实践取向",
      "high": "立足于实践行动——哲学是为了生活，而非仅止于思辨",
      "low": "倾向于将思考本身视为目的，无关乎即时的实用价值"
    }
  },
  "TD": {
    "zh": {
      "label": "理论驱力",
      "high": "倾向于宏大的体系与深层的结构",
      "low": "不信任宏大体系——偏爱具体、审慎的论断"
    }
  },
  "AT": {
    "zh": {
      "label": "禁欲倾向",
      "high": "重视自律而非放纵——功夫在于节制",
      "low": "认为自我克制并无美德可言——安排得宜的享乐本是美好生活的一部分"
    }
  },
  "ES": {
    "zh": {
      "label": "身体感性",
      "high": "认真对待身体与感官——具身的生活才是真实的生活",
      "low": "倾向于以心驭身——感官不过是靠不住的证人"
    }
  },
  "UI": {
    "zh": {
      "label": "普遍主义冲动",
      "high": "寻求对所有人都成立的原则，而非仅适用于某一群体",
      "low": "植根于具体特殊之物——地方性与个别性重于抽象的普遍性"
    }
  },
  "SI": {
    "zh": {
      "label": "自我作为幻象",
      "high": "视自我为一种有用的虚构——其下并无固定的\"你\"",
      "low": "体验到自我的真实与连续——有一个\"你\"在发出追问"
    }
  }
};
// ─── END gen-translate DIM_NARRATION_I18N ───

/** Look up the translated narration fragments for one dimension. Returns
 *  undefined when the dim/locale has no entry (caller falls back to the
 *  English DIM_NARRATIONS source). */
export function getLocalizedDimNarration(
  key: string,
  locale: Locale,
): DimNarrationI18nFields | undefined {
  return DIM_NARRATION_I18N[key]?.[locale];
}

// Degree qualifiers, per locale. Hand-maintained (tiny, closed set). The
// three buckets correspond to distance from the scale midpoint:
//   strong   — 3+ away   ("strongly")
//   moderate — 1–3 away  ("moderately")
//   barely   — <1 away   ("just barely")
//
// Only locales present here use the prefix template; anything missing
// falls through to the English splice in poleSentence(). en is included
// for completeness but the English path doesn't read it.
export type NarrationQualifiers = { strong: string; moderate: string; barely: string };

export const NARRATION_QUALIFIERS: Partial<Record<Locale, NarrationQualifiers>> = {
  en: { strong: 'strongly', moderate: 'moderately', barely: 'just barely' },
  zh: { strong: '强烈地', moderate: '较为', barely: '略微' },
};
