// Auto-extracted from public/mull.html PHILOSOPHERS array, enriched with
// nearest-archetype mapping and search aliases (first names, alternate
// spellings) for prominent philosophers.

export type PhilosopherEntry = {
  name: string;
  dates: string;
  keyIdea: string;
  vector: number[];
  archetypeKey: string;
  archetypeName: string;
  aliases: string[];
};

export const PHILOSOPHERS: PhilosopherEntry[] = [
  {
    "name": "Heraclitus",
    "dates": "~535–475 BCE",
    "keyIdea": "Everything flows. You can't step in the same river twice. The hidden harmony is stronger than the visible one.",
    "vector": [
      6,
      7,
      5,
      5,
      7,
      3,
      7,
      5,
      3,
      5,
      4,
      8,
      3,
      5,
      5,
      8
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Plato",
    "dates": "~428–348 BCE",
    "keyIdea": "The visible world is a shadow of the eternal Forms. Knowledge is recollection; the soul climbs from appearance to reality through reason.",
    "vector": [
      5,
      5,
      5,
      10,
      2,
      3,
      7,
      2,
      5,
      4,
      6,
      10,
      7,
      2,
      10,
      3
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "platonism"
    ]
  },
  {
    "name": "Aristotle",
    "dates": "384–322 BCE",
    "keyIdea": "Virtue is a stable disposition cultivated through practice. The good life is the active life of excellence in accord with reason.",
    "vector": [
      4,
      7,
      3,
      8,
      8,
      6,
      2,
      3,
      7,
      4,
      8,
      8,
      5,
      6,
      5,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Diogenes of Sinope",
    "dates": "~412–323 BCE",
    "keyIdea": "Lived in a barrel. Called himself a citizen of the cosmos. Rejected convention to live according to nature.",
    "vector": [
      5,
      6,
      7,
      4,
      7,
      1,
      2,
      8,
      2,
      10,
      9,
      3,
      8,
      3,
      5,
      3
    ],
    "archetypeKey": "hammer",
    "archetypeName": "The Hammer",
    "aliases": [
      "diogenes"
    ]
  },
  {
    "name": "Epicurus",
    "dates": "341–270 BCE",
    "keyIdea": "The art of happiness is the absence of pain. Live simply, cultivate friendship, don't fear death.",
    "vector": [
      3,
      8,
      3,
      6,
      9,
      2,
      1,
      7,
      6,
      6,
      9,
      5,
      3,
      9,
      4,
      4
    ],
    "archetypeKey": "garden",
    "archetypeName": "The Garden",
    "aliases": [
      "epicurean"
    ]
  },
  {
    "name": "Epictetus",
    "dates": "50–135 CE",
    "keyIdea": "It's not what happens to you, but how you respond. Some things are up to us; most things are not.",
    "vector": [
      7,
      6,
      3,
      8,
      6,
      6,
      3,
      5,
      5,
      6,
      10,
      5,
      9,
      3,
      7,
      4
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  },
  {
    "name": "Marcus Aurelius",
    "dates": "121–180 CE",
    "keyIdea": "You can't control what happens to you. You can control how you meet it. The work of life is in your response, not the world.",
    "vector": [
      7,
      6,
      2,
      8,
      6,
      6,
      3,
      4,
      6,
      5,
      10,
      5,
      8,
      3,
      7,
      3
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": [
      "marcus",
      "aurelius"
    ]
  },
  {
    "name": "Plotinus",
    "dates": "~204–270 CE",
    "keyIdea": "All things flow from the One. The soul ascends through contemplation back to its source.",
    "vector": [
      5,
      5,
      3,
      9,
      2,
      5,
      10,
      2,
      5,
      4,
      5,
      9,
      8,
      1,
      9,
      7
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Augustine",
    "dates": "354–430",
    "keyIdea": "Our hearts are restless until they rest in Thee. Memory, will, understanding mirror the Trinity.",
    "vector": [
      8,
      5,
      4,
      8,
      4,
      9,
      9,
      3,
      8,
      4,
      7,
      8,
      8,
      2,
      9,
      3
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "saint augustine",
      "hippo"
    ]
  },
  {
    "name": "Thomas Aquinas",
    "dates": "1225–1274",
    "keyIdea": "Faith and reason are complementary. Natural law underlies divine law. Five ways to demonstrate God.",
    "vector": [
      5,
      6,
      3,
      9,
      7,
      9,
      6,
      2,
      8,
      4,
      7,
      9,
      6,
      4,
      9,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Meister Eckhart",
    "dates": "~1260–1328",
    "keyIdea": "Become as nothing. The eye through which I see God is the same eye through which God sees me.",
    "vector": [
      6,
      5,
      1,
      5,
      3,
      7,
      10,
      4,
      5,
      2,
      6,
      6,
      9,
      1,
      8,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Maimonides",
    "dates": "1138–1204",
    "keyIdea": "We can only say what God is not. Reason and revelation align in their highest reaches.",
    "vector": [
      5,
      5,
      3,
      9,
      5,
      9,
      6,
      4,
      8,
      4,
      7,
      9,
      7,
      3,
      9,
      3
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "moses",
      "rambam"
    ]
  },
  {
    "name": "Spinoza",
    "dates": "1632–1677",
    "keyIdea": "God or Nature. Everything that is, is in God. Freedom is understanding necessity.",
    "vector": [
      5,
      6,
      3,
      10,
      7,
      2,
      7,
      6,
      5,
      5,
      6,
      10,
      6,
      4,
      10,
      6
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "baruch",
      "benedict"
    ]
  },
  {
    "name": "Mary Wollstonecraft",
    "dates": "1759–1797",
    "keyIdea": "Women's rights are human rights. Reason knows no gender. Education emancipates.",
    "vector": [
      4,
      7,
      7,
      9,
      7,
      2,
      1,
      5,
      6,
      8,
      8,
      6,
      3,
      5,
      9,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Al-Farabi",
    "dates": "~872–950",
    "keyIdea": "The virtuous city imitates the cosmic order. Philosophy and religion express the same truth in different registers.",
    "vector": [
      4,
      5,
      3,
      9,
      5,
      7,
      5,
      2,
      8,
      4,
      7,
      9,
      5,
      3,
      9,
      2
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Ibn Sina (Avicenna)",
    "dates": "980–1037",
    "keyIdea": "Necessary Existent argument for God. The 'floating man' shows soul as substance distinct from body.",
    "vector": [
      4,
      5,
      3,
      9,
      7,
      7,
      5,
      3,
      6,
      5,
      6,
      9,
      5,
      4,
      8,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Al-Ghazali",
    "dates": "1058–1111",
    "keyIdea": "Reason has limits. Direct experience of the divine through Sufi practice. Doubt led me back to faith.",
    "vector": [
      6,
      5,
      2,
      5,
      6,
      9,
      9,
      7,
      8,
      3,
      7,
      6,
      8,
      2,
      9,
      5
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "ghazali"
    ]
  },
  {
    "name": "Ibn Rushd (Averroes)",
    "dates": "1126–1198",
    "keyIdea": "Reason and revelation agree. Defense of philosophy against Al-Ghazali. The Aristotelian commentaries.",
    "vector": [
      3,
      6,
      4,
      10,
      7,
      7,
      3,
      4,
      6,
      5,
      7,
      9,
      5,
      4,
      8,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Ibn Arabi",
    "dates": "1165–1240",
    "keyIdea": "Wahdat al-wujud — the unity of being. The world is God's self-manifestation. Imagination is creative.",
    "vector": [
      5,
      6,
      3,
      7,
      4,
      7,
      10,
      3,
      6,
      3,
      5,
      8,
      7,
      3,
      9,
      8
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Rumi",
    "dates": "1207–1273",
    "keyIdea": "The reed cut from the reed-bed cries of separation. Love is the bridge between you and everything.",
    "vector": [
      6,
      8,
      2,
      3,
      5,
      7,
      10,
      3,
      8,
      3,
      6,
      4,
      6,
      6,
      8,
      8
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "jalal",
      "mevlana"
    ]
  },
  {
    "name": "Patanjali",
    "dates": "~200 BCE",
    "keyIdea": "Yoga is the cessation of mental fluctuations. Eight limbs leading to samadhi.",
    "vector": [
      5,
      5,
      3,
      6,
      7,
      7,
      9,
      4,
      5,
      4,
      9,
      6,
      9,
      3,
      7,
      8
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Adi Shankara",
    "dates": "~788–820",
    "keyIdea": "Brahman alone is real. The world is illusion. Atman = Brahman. Liberation through knowledge.",
    "vector": [
      7,
      4,
      2,
      8,
      3,
      8,
      10,
      4,
      5,
      2,
      6,
      8,
      9,
      1,
      9,
      10
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Ramanuja",
    "dates": "1017–1137",
    "keyIdea": "Qualified non-dualism. Devotion is the path. The soul is real, distinct from yet inseparable from God.",
    "vector": [
      4,
      7,
      3,
      7,
      5,
      9,
      9,
      3,
      8,
      3,
      7,
      7,
      6,
      3,
      8,
      5
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Aurobindo",
    "dates": "1872–1950",
    "keyIdea": "Spirit descending into matter is evolving back to spirit. Future humanity will be divine humanity.",
    "vector": [
      4,
      8,
      6,
      7,
      6,
      6,
      9,
      3,
      7,
      5,
      7,
      8,
      6,
      5,
      8,
      6
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Krishnamurti",
    "dates": "1895–1986",
    "keyIdea": "Truth is a pathless land. Question all authority. Freedom is in direct seeing, not in following.",
    "vector": [
      5,
      6,
      1,
      4,
      7,
      1,
      9,
      9,
      3,
      7,
      7,
      5,
      7,
      5,
      5,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "jiddu"
    ]
  },
  {
    "name": "Tagore",
    "dates": "1861–1941",
    "keyIdea": "Where the mind is without fear. The boundless sky of personality. Nature and humanity in unity.",
    "vector": [
      5,
      8,
      3,
      5,
      7,
      6,
      8,
      3,
      8,
      6,
      5,
      5,
      3,
      6,
      7,
      5
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "rabindranath"
    ]
  },
  {
    "name": "Gandhi",
    "dates": "1869–1948",
    "keyIdea": "Satyagraha — truth-force. Non-violent resistance. Be the change you wish to see.",
    "vector": [
      6,
      7,
      5,
      5,
      7,
      8,
      8,
      4,
      9,
      6,
      9,
      5,
      9,
      3,
      9,
      5
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": [
      "mohandas",
      "mahatma"
    ]
  },
  {
    "name": "Buddha",
    "dates": "~563–483 BCE",
    "keyIdea": "Suffering is the first noble truth. The self that suffers is itself the illusion. Walk the eightfold path.",
    "vector": [
      10,
      4,
      2,
      4,
      8,
      4,
      9,
      6,
      7,
      2,
      10,
      4,
      10,
      2,
      8,
      10
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "siddhartha",
      "gautama",
      "shakyamuni"
    ]
  },
  {
    "name": "Mahavira",
    "dates": "599–527 BCE",
    "keyIdea": "Ahimsa above all. Many-sided reality (anekantavada). Liberation through asceticism.",
    "vector": [
      8,
      4,
      1,
      7,
      6,
      7,
      7,
      6,
      6,
      3,
      9,
      6,
      10,
      1,
      10,
      7
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Nagarjuna",
    "dates": "~150–250 CE",
    "keyIdea": "All phenomena are empty of inherent existence. Two truths: conventional and ultimate. The middle way.",
    "vector": [
      8,
      4,
      1,
      8,
      4,
      5,
      9,
      9,
      6,
      1,
      8,
      8,
      9,
      1,
      8,
      10
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Laozi",
    "dates": "~6th c. BCE",
    "keyIdea": "The way that can be spoken is not the eternal way. Wei wu wei — effortless action.",
    "vector": [
      6,
      6,
      1,
      3,
      7,
      4,
      9,
      5,
      5,
      5,
      8,
      5,
      7,
      5,
      6,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "lao tzu",
      "lao"
    ]
  },
  {
    "name": "Confucius",
    "dates": "~551–479 BCE",
    "keyIdea": "Cultivate the self through ritual and relation. The good life is the well-ordered life inside a well-ordered community.",
    "vector": [
      4,
      6,
      3,
      5,
      7,
      10,
      2,
      2,
      10,
      2,
      10,
      3,
      5,
      4,
      4,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "kong",
      "kongzi"
    ]
  },
  {
    "name": "Mozi",
    "dates": "~470–391 BCE",
    "keyIdea": "Impartial care for all. Utility as the standard. Against extravagance and elaborate funerals.",
    "vector": [
      4,
      5,
      7,
      8,
      8,
      2,
      1,
      6,
      8,
      3,
      9,
      5,
      7,
      3,
      10,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "mo zi",
      "mo di"
    ]
  },
  {
    "name": "Mencius",
    "dates": "372–289 BCE",
    "keyIdea": "Human nature is fundamentally good. The four sprouts of virtue need only cultivation.",
    "vector": [
      3,
      7,
      4,
      6,
      7,
      9,
      3,
      2,
      9,
      3,
      9,
      5,
      5,
      5,
      6,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "mengzi"
    ]
  },
  {
    "name": "Zhuangzi",
    "dates": "~369–286 BCE",
    "keyIdea": "Was I a man dreaming I was a butterfly, or a butterfly dreaming I was a man? The free play of mind.",
    "vector": [
      5,
      8,
      2,
      3,
      6,
      3,
      8,
      8,
      4,
      7,
      6,
      7,
      5,
      6,
      5,
      9
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "chuang tzu"
    ]
  },
  {
    "name": "Xunzi",
    "dates": "~310–235 BCE",
    "keyIdea": "Human nature is flawed. Ritual and education civilize us. Heaven follows constant patterns.",
    "vector": [
      5,
      5,
      5,
      8,
      8,
      9,
      1,
      5,
      9,
      3,
      9,
      6,
      6,
      4,
      6,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "xun zi"
    ]
  },
  {
    "name": "Dogen",
    "dates": "1200–1253",
    "keyIdea": "Practice and enlightenment are one. Just sitting (shikantaza). Being-time: time itself is being.",
    "vector": [
      6,
      6,
      2,
      4,
      8,
      7,
      10,
      5,
      7,
      3,
      9,
      5,
      9,
      4,
      7,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Nishida Kitarō",
    "dates": "1870–1945",
    "keyIdea": "Pure experience precedes the subject-object distinction. Place of nothingness as ground of being.",
    "vector": [
      5,
      6,
      3,
      8,
      6,
      6,
      8,
      4,
      6,
      4,
      5,
      9,
      5,
      4,
      7,
      8
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Anton Wilhelm Amo",
    "dates": "1703–1759",
    "keyIdea": "Mind and body are distinct. African capacity for philosophical reasoning is equal to any.",
    "vector": [
      4,
      6,
      5,
      9,
      6,
      5,
      1,
      5,
      5,
      7,
      6,
      8,
      5,
      3,
      9,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "W.E.B. Du Bois",
    "dates": "1868–1963",
    "keyIdea": "Double consciousness — always seeing yourself through the eyes of others. The problem of the color line.",
    "vector": [
      7,
      6,
      7,
      7,
      8,
      4,
      3,
      6,
      9,
      6,
      7,
      7,
      4,
      5,
      7,
      4
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Frantz Fanon",
    "dates": "1925–1961",
    "keyIdea": "The wretched of the earth must speak for themselves. Decolonization is the violent refusal of imposed being.",
    "vector": [
      8,
      7,
      9,
      6,
      8,
      2,
      1,
      7,
      8,
      7,
      8,
      5,
      3,
      6,
      7,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Kwasi Wiredu",
    "dates": "1931–2022",
    "keyIdea": "Conceptual decolonization. Truth in Akan thought. Consensus over majority rule.",
    "vector": [
      3,
      6,
      5,
      7,
      8,
      8,
      3,
      5,
      9,
      4,
      8,
      7,
      3,
      5,
      6,
      3
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Audre Lorde",
    "dates": "1934–1992",
    "keyIdea": "The master's tools will never dismantle the master's house. Difference is creative power.",
    "vector": [
      6,
      7,
      7,
      5,
      8,
      2,
      5,
      7,
      8,
      7,
      7,
      5,
      3,
      6,
      6,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "bell hooks",
    "dates": "1952–2021",
    "keyIdea": "Love as transformative practice. Engaged pedagogy. Patriarchy hurts everyone.",
    "vector": [
      4,
      7,
      6,
      6,
      8,
      3,
      4,
      6,
      9,
      6,
      8,
      6,
      3,
      6,
      7,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Hume",
    "dates": "1711–1776",
    "keyIdea": "Reason is the slave of the passions. The self is a bundle of perceptions. Doubt every claim that goes beyond experience.",
    "vector": [
      4,
      6,
      3,
      4,
      10,
      5,
      0,
      10,
      4,
      6,
      7,
      8,
      2,
      6,
      3,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": [
      "david hume",
      "david"
    ]
  },
  {
    "name": "Kant",
    "dates": "1724–1804",
    "keyIdea": "Treat every person as an end. Universal moral law is reachable through reason alone.",
    "vector": [
      4,
      4,
      2,
      10,
      3,
      4,
      2,
      2,
      4,
      6,
      6,
      8,
      8,
      2,
      10,
      2
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "immanuel"
    ]
  },
  {
    "name": "Hegel",
    "dates": "1770–1831",
    "keyIdea": "The real is the rational. Spirit unfolds through history. Thesis, antithesis, synthesis.",
    "vector": [
      5,
      6,
      5,
      10,
      5,
      6,
      6,
      3,
      8,
      5,
      5,
      10,
      5,
      3,
      9,
      4
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "georg"
    ]
  },
  {
    "name": "Schopenhauer",
    "dates": "1788–1860",
    "keyIdea": "The world is will and representation. Life is suffering punctuated by boredom.",
    "vector": [
      10,
      3,
      3,
      7,
      6,
      4,
      7,
      7,
      3,
      6,
      6,
      9,
      9,
      4,
      5,
      6
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": [
      "arthur"
    ]
  },
  {
    "name": "Mill",
    "dates": "1806–1873",
    "keyIdea": "The greatest happiness of the greatest number. Defend liberty fiercely; reform what harms slowly and durably.",
    "vector": [
      3,
      7,
      4,
      6,
      8,
      2,
      1,
      4,
      3,
      8,
      8,
      5,
      2,
      6,
      8,
      2
    ],
    "archetypeKey": "garden",
    "archetypeName": "The Garden",
    "aliases": [
      "john stuart",
      "jsm"
    ]
  },
  {
    "name": "Kierkegaard",
    "dates": "1813–1855",
    "keyIdea": "Subjectivity is truth. The leap of faith. Three stages: aesthetic, ethical, religious.",
    "vector": [
      9,
      6,
      4,
      5,
      5,
      5,
      9,
      6,
      4,
      9,
      6,
      7,
      7,
      3,
      6,
      4
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "soren",
      "søren"
    ]
  },
  {
    "name": "Marx",
    "dates": "1818–1883",
    "keyIdea": "Material conditions shape consciousness. The point is not to interpret the world but to change it.",
    "vector": [
      6,
      5,
      10,
      7,
      8,
      1,
      0,
      5,
      10,
      3,
      8,
      7,
      3,
      5,
      7,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "karl",
      "karl marx"
    ]
  },
  {
    "name": "Nietzsche",
    "dates": "1844–1900",
    "keyIdea": "Affirm life despite its tragedy. Become who you are. Suspect every value you inherited; revalue all values.",
    "vector": [
      9,
      10,
      10,
      3,
      6,
      2,
      3,
      8,
      2,
      10,
      7,
      6,
      4,
      7,
      2,
      4
    ],
    "archetypeKey": "hammer",
    "archetypeName": "The Hammer",
    "aliases": [
      "friedrich"
    ]
  },
  {
    "name": "William James",
    "dates": "1842–1910",
    "keyIdea": "Truth is what works. The varieties of religious experience. The will to believe.",
    "vector": [
      5,
      7,
      5,
      6,
      9,
      4,
      7,
      5,
      6,
      7,
      9,
      6,
      3,
      5,
      5,
      5
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "John Dewey",
    "dates": "1859–1952",
    "keyIdea": "Democracy is more than government. Learning by doing. Inquiry as the model of all thought.",
    "vector": [
      3,
      7,
      6,
      7,
      9,
      3,
      1,
      5,
      9,
      5,
      9,
      6,
      2,
      5,
      7,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Husserl",
    "dates": "1859–1938",
    "keyIdea": "Bracket your assumptions and return to the things themselves. Phenomenology as rigorous science.",
    "vector": [
      4,
      5,
      3,
      8,
      7,
      4,
      5,
      5,
      5,
      5,
      5,
      9,
      5,
      5,
      7,
      4
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": [
      "edmund husserl"
    ]
  },
  {
    "name": "Wittgenstein",
    "dates": "1889–1951",
    "keyIdea": "The limits of my language are the limits of my world. Whereof one cannot speak, thereof one must be silent.",
    "vector": [
      6,
      5,
      3,
      6,
      8,
      5,
      7,
      9,
      5,
      7,
      6,
      9,
      7,
      4,
      4,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": [
      "ludwig"
    ]
  },
  {
    "name": "Heidegger",
    "dates": "1889–1976",
    "keyIdea": "Being-toward-death. Dasein. The forgetting of Being. Authenticity through resoluteness.",
    "vector": [
      9,
      6,
      4,
      6,
      7,
      6,
      7,
      5,
      5,
      8,
      6,
      9,
      5,
      5,
      4,
      6
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "martin"
    ]
  },
  {
    "name": "Sartre",
    "dates": "1905–1980",
    "keyIdea": "You are condemned to be free. There is no human nature to fall back on. Choose, and own the choice.",
    "vector": [
      8,
      6,
      7,
      6,
      5,
      2,
      1,
      6,
      4,
      10,
      7,
      7,
      3,
      4,
      4,
      3
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "jean-paul",
      "jean paul"
    ]
  },
  {
    "name": "Hannah Arendt",
    "dates": "1906–1975",
    "keyIdea": "The banality of evil. Action and natality. The public realm is the space of appearance.",
    "vector": [
      6,
      7,
      6,
      7,
      7,
      5,
      2,
      6,
      9,
      7,
      8,
      7,
      4,
      5,
      6,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Levinas",
    "dates": "1906–1995",
    "keyIdea": "The face of the Other interrupts you. Ethics is first philosophy, before being.",
    "vector": [
      7,
      5,
      2,
      6,
      6,
      6,
      7,
      5,
      9,
      4,
      7,
      7,
      6,
      4,
      9,
      5
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": [
      "emmanuel"
    ]
  },
  {
    "name": "Simone de Beauvoir",
    "dates": "1908–1986",
    "keyIdea": "Existentialism with company. Freedom is real but lived through and against the freedom of others. One is not born, but becomes.",
    "vector": [
      7,
      7,
      7,
      6,
      7,
      2,
      1,
      6,
      8,
      9,
      8,
      6,
      3,
      6,
      5,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "G.E.M. Anscombe",
    "dates": "1919–2001",
    "keyIdea": "Modern moral philosophy is bankrupt. Return to virtue. Intention shapes action.",
    "vector": [
      5,
      5,
      2,
      9,
      5,
      8,
      5,
      4,
      8,
      4,
      8,
      8,
      7,
      3,
      7,
      2
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  },
  {
    "name": "John Rawls",
    "dates": "1921–2002",
    "keyIdea": "Justice as fairness. Choose principles behind a veil of ignorance. The least advantaged must benefit.",
    "vector": [
      4,
      5,
      5,
      9,
      7,
      3,
      1,
      4,
      7,
      5,
      7,
      8,
      4,
      3,
      10,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Foucault",
    "dates": "1926–1984",
    "keyIdea": "Power is everywhere. Knowledge is never innocent. The genealogy of the modern subject.",
    "vector": [
      7,
      5,
      9,
      6,
      9,
      1,
      1,
      9,
      6,
      6,
      7,
      8,
      3,
      5,
      3,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": [
      "michel"
    ]
  },
  {
    "name": "Ayn Rand",
    "dates": "1905–1982",
    "keyIdea": "Rational self-interest is moral. Capitalism is the only system consistent with reason. Altruism is a fraud.",
    "vector": [
      2,
      10,
      10,
      10,
      4,
      1,
      0,
      5,
      1,
      10,
      8,
      6,
      3,
      7,
      6,
      1
    ],
    "archetypeKey": "hammer",
    "archetypeName": "The Hammer",
    "aliases": []
  },
  {
    "name": "Derek Parfit",
    "dates": "1942–2017",
    "keyIdea": "Personal identity is not what matters. Reasons and persons. Reduce the self; expand the moral circle.",
    "vector": [
      5,
      5,
      3,
      10,
      6,
      2,
      2,
      5,
      5,
      3,
      5,
      10,
      5,
      3,
      9,
      9
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Pythagoras",
    "dates": "~570–495 BCE",
    "keyIdea": "Number is the essence of all things. The cosmos is mathematical music. Life is purification of the soul through reason.",
    "vector": [
      4,
      5,
      3,
      8,
      5,
      8,
      8,
      2,
      7,
      3,
      7,
      8,
      7,
      3,
      8,
      3
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Parmenides",
    "dates": "~515–450 BCE",
    "keyIdea": "Being is one, eternal, unchanging. Change is illusion. Only what is, is.",
    "vector": [
      3,
      4,
      1,
      10,
      1,
      5,
      5,
      5,
      3,
      4,
      3,
      10,
      5,
      1,
      9,
      5
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Empedocles",
    "dates": "~494–434 BCE",
    "keyIdea": "Four roots: earth, air, fire, water. Love and Strife alternate. The sphere of being cycles.",
    "vector": [
      4,
      6,
      3,
      6,
      7,
      5,
      7,
      3,
      5,
      4,
      5,
      7,
      5,
      5,
      6,
      4
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Protagoras",
    "dates": "~490–420 BCE",
    "keyIdea": "Man is the measure of all things. Truth is relative to the perceiver.",
    "vector": [
      3,
      7,
      5,
      5,
      9,
      2,
      1,
      8,
      7,
      6,
      8,
      5,
      2,
      6,
      2,
      5
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Pyrrho",
    "dates": "~360–270 BCE",
    "keyIdea": "Suspend judgment. Reach tranquility through accepting the impossibility of certainty.",
    "vector": [
      5,
      4,
      1,
      2,
      6,
      2,
      5,
      10,
      3,
      6,
      7,
      5,
      8,
      3,
      1,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Sextus Empiricus",
    "dates": "~160–210 CE",
    "keyIdea": "For every argument an equal counter-argument. Live by appearances; suspend belief.",
    "vector": [
      4,
      5,
      1,
      3,
      7,
      3,
      1,
      10,
      4,
      5,
      7,
      7,
      5,
      4,
      1,
      5
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Seneca",
    "dates": "~4 BCE–65 CE",
    "keyIdea": "Time is the most valuable thing. Even slaves are equal in soul. Bear what comes; embrace mortality.",
    "vector": [
      7,
      6,
      3,
      8,
      6,
      7,
      3,
      4,
      7,
      5,
      9,
      5,
      8,
      3,
      7,
      3
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": [
      "lucius"
    ]
  },
  {
    "name": "Cicero",
    "dates": "106–43 BCE",
    "keyIdea": "Eclectic synthesis of Greek thought. Natural law underlies just government. Duty to community.",
    "vector": [
      5,
      6,
      5,
      8,
      7,
      8,
      3,
      5,
      8,
      5,
      9,
      7,
      5,
      4,
      8,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Lucretius",
    "dates": "~99–55 BCE",
    "keyIdea": "Atoms swerving freely create the world. Religion breeds fear. Death is nothing to us.",
    "vector": [
      4,
      8,
      3,
      6,
      9,
      1,
      0,
      7,
      5,
      6,
      8,
      7,
      3,
      8,
      4,
      6
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Anselm",
    "dates": "1033–1109",
    "keyIdea": "That than which nothing greater can be conceived must exist. Faith seeking understanding.",
    "vector": [
      4,
      5,
      2,
      9,
      3,
      9,
      8,
      2,
      7,
      3,
      5,
      9,
      7,
      1,
      9,
      2
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "saint anselm"
    ]
  },
  {
    "name": "William of Ockham",
    "dates": "~1287–1347",
    "keyIdea": "Multiply not entities beyond necessity. Universals are linguistic conveniences, not realities.",
    "vector": [
      3,
      5,
      2,
      8,
      7,
      6,
      4,
      7,
      6,
      5,
      5,
      8,
      6,
      3,
      6,
      4
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Hildegard of Bingen",
    "dates": "1098–1179",
    "keyIdea": "Visions of God's living light. Viriditas — the greening power. Body and soul are sacred unity.",
    "vector": [
      5,
      7,
      3,
      5,
      5,
      8,
      10,
      2,
      8,
      4,
      6,
      6,
      7,
      5,
      8,
      4
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Catherine of Siena",
    "dates": "1347–1380",
    "keyIdea": "Mystical union with Christ. The cell of self-knowledge. Bridge between God and humanity.",
    "vector": [
      6,
      6,
      4,
      5,
      5,
      8,
      9,
      2,
      8,
      5,
      7,
      5,
      9,
      2,
      8,
      4
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  },
  {
    "name": "Nicholas of Cusa",
    "dates": "1401–1464",
    "keyIdea": "Learned ignorance. The coincidence of opposites. The infinite contains all finite.",
    "vector": [
      4,
      6,
      2,
      9,
      5,
      7,
      9,
      5,
      6,
      4,
      5,
      10,
      6,
      3,
      9,
      5
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Teresa of Ávila",
    "dates": "1515–1582",
    "keyIdea": "Interior castle with seven mansions. Mystical prayer leads to union with God.",
    "vector": [
      5,
      6,
      3,
      5,
      7,
      8,
      10,
      2,
      7,
      4,
      7,
      5,
      8,
      3,
      8,
      5
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "John of the Cross",
    "dates": "1542–1591",
    "keyIdea": "The dark night of the soul. Nada y todo — nothing and all. Strip away to find God.",
    "vector": [
      7,
      5,
      1,
      5,
      5,
      8,
      10,
      3,
      5,
      4,
      6,
      6,
      9,
      1,
      8,
      6
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Julian of Norwich",
    "dates": "~1342–1416",
    "keyIdea": "All shall be well. Sin is necessary, but love prevails. God as Mother.",
    "vector": [
      5,
      7,
      2,
      4,
      6,
      7,
      9,
      3,
      7,
      4,
      6,
      5,
      6,
      4,
      8,
      4
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Erasmus",
    "dates": "1466–1536",
    "keyIdea": "Folly speaks truth. Reform within tradition. The dignity of conversation and learning.",
    "vector": [
      4,
      7,
      3,
      8,
      7,
      6,
      4,
      6,
      7,
      6,
      7,
      7,
      4,
      5,
      8,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Machiavelli",
    "dates": "1469–1527",
    "keyIdea": "Politics requires virtù — practical wisdom. Better to be feared than loved. Read history honestly.",
    "vector": [
      7,
      6,
      8,
      7,
      9,
      4,
      0,
      8,
      5,
      6,
      10,
      5,
      3,
      4,
      2,
      3
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Pascal",
    "dates": "1623–1662",
    "keyIdea": "The eternal silence of infinite spaces frightens me. The heart has reasons reason knows not. Wager on God.",
    "vector": [
      9,
      5,
      2,
      7,
      6,
      7,
      8,
      7,
      5,
      6,
      7,
      7,
      7,
      3,
      7,
      5
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  },
  {
    "name": "Al-Kindi",
    "dates": "~801–873",
    "keyIdea": "Philosophy and revelation come from the same divine source. Truth cares nothing for who utters it.",
    "vector": [
      3,
      6,
      3,
      9,
      6,
      7,
      5,
      3,
      6,
      4,
      6,
      9,
      5,
      3,
      8,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Ibn Tufayl",
    "dates": "~1105–1185",
    "keyIdea": "Hayy ibn Yaqzan grows up alone on an island and reasons his way to mystical truth.",
    "vector": [
      4,
      6,
      2,
      8,
      6,
      5,
      8,
      4,
      5,
      7,
      6,
      8,
      7,
      3,
      7,
      4
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Mulla Sadra",
    "dates": "1571–1640",
    "keyIdea": "Existence precedes essence. Reality of being intensifies through gradation. Trans-substantial motion.",
    "vector": [
      5,
      6,
      3,
      8,
      5,
      7,
      9,
      3,
      6,
      4,
      5,
      9,
      6,
      3,
      8,
      6
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Madhva",
    "dates": "1238–1317",
    "keyIdea": "Strict dualism. The soul is eternally distinct from God. Devotion is the path.",
    "vector": [
      4,
      6,
      3,
      7,
      6,
      9,
      7,
      2,
      8,
      4,
      7,
      7,
      5,
      4,
      7,
      3
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Vivekananda",
    "dates": "1863–1902",
    "keyIdea": "Arise, awake, stop not till the goal is reached. Each soul is potentially divine. Practical Vedanta.",
    "vector": [
      3,
      9,
      8,
      6,
      7,
      6,
      9,
      3,
      7,
      8,
      8,
      6,
      5,
      5,
      9,
      6
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Ramana Maharshi",
    "dates": "1879–1950",
    "keyIdea": "Who am I? Trace the I-thought to its source. The Self alone is real.",
    "vector": [
      4,
      5,
      1,
      4,
      7,
      5,
      10,
      5,
      3,
      3,
      8,
      4,
      8,
      3,
      6,
      10
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Nisargadatta Maharaj",
    "dates": "1897–1981",
    "keyIdea": "I Am That. Before all conditioning, you are pure awareness. Find the source.",
    "vector": [
      4,
      6,
      1,
      5,
      7,
      3,
      9,
      7,
      3,
      4,
      8,
      5,
      6,
      4,
      6,
      10
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Bodhidharma",
    "dates": "~470–~543",
    "keyIdea": "A special transmission outside the scriptures. Direct pointing at the mind. See your own nature.",
    "vector": [
      6,
      5,
      5,
      3,
      8,
      4,
      9,
      7,
      4,
      7,
      9,
      3,
      9,
      4,
      6,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Hui Neng",
    "dates": "638–713",
    "keyIdea": "From the beginning, not a thing is. Sudden enlightenment. Cut through illusion to original mind.",
    "vector": [
      5,
      7,
      3,
      3,
      8,
      4,
      9,
      6,
      5,
      5,
      9,
      3,
      6,
      5,
      7,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Tsongkhapa",
    "dates": "1357–1419",
    "keyIdea": "Synthesis of sutra and tantra. Emptiness combined with rigorous logic. Lamrim — the graduated path.",
    "vector": [
      6,
      5,
      3,
      9,
      6,
      8,
      8,
      5,
      7,
      3,
      8,
      8,
      8,
      2,
      8,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Thich Nhat Hanh",
    "dates": "1926–2022",
    "keyIdea": "Engaged Buddhism. Mindfulness as the heart of practice. Interbeing — we are made of non-self elements.",
    "vector": [
      5,
      8,
      3,
      4,
      8,
      6,
      8,
      4,
      9,
      4,
      10,
      4,
      6,
      5,
      8,
      8
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Dalai Lama (14th)",
    "dates": "b. 1935",
    "keyIdea": "Compassion is the foundation. Inner peace is the source of outer peace. My religion is kindness.",
    "vector": [
      5,
      8,
      3,
      6,
      7,
      8,
      8,
      4,
      9,
      4,
      10,
      5,
      6,
      4,
      9,
      8
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Han Feizi",
    "dates": "~280–233 BCE",
    "keyIdea": "Strict laws and harsh punishments. Trust no one. Power, position, technique — the ruler's tools.",
    "vector": [
      6,
      5,
      9,
      8,
      8,
      3,
      0,
      8,
      6,
      6,
      10,
      6,
      6,
      3,
      5,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Wang Yangming",
    "dates": "1472–1529",
    "keyIdea": "Innate moral knowledge. Knowledge and action are one. Investigate the heart, not external things.",
    "vector": [
      4,
      7,
      5,
      6,
      8,
      6,
      6,
      3,
      8,
      6,
      9,
      6,
      5,
      4,
      6,
      4
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "wang yang-ming"
    ]
  },
  {
    "name": "Zhu Xi",
    "dates": "1130–1200",
    "keyIdea": "The investigation of things. Principle (li) and material force (qi). Rigorous Confucian synthesis.",
    "vector": [
      4,
      5,
      3,
      8,
      7,
      9,
      5,
      2,
      9,
      3,
      8,
      8,
      7,
      3,
      7,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Kūkai",
    "dates": "774–835",
    "keyIdea": "Become a Buddha in this very body. Mantras, mudras, mandalas. Esoteric Buddhism in Japan.",
    "vector": [
      5,
      7,
      4,
      6,
      6,
      8,
      10,
      3,
      7,
      5,
      8,
      7,
      6,
      5,
      8,
      7
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Hakuin",
    "dates": "1686–1769",
    "keyIdea": "What is the sound of one hand clapping? The great doubt leads to great awakening.",
    "vector": [
      6,
      7,
      5,
      3,
      8,
      7,
      9,
      5,
      6,
      6,
      9,
      4,
      8,
      4,
      7,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Watsuji Tetsurō",
    "dates": "1889–1960",
    "keyIdea": "Climate and culture shape ethics. The self is constituted by relationships, not standalone.",
    "vector": [
      5,
      6,
      3,
      7,
      8,
      8,
      5,
      3,
      9,
      3,
      7,
      7,
      5,
      5,
      5,
      5
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Hillel",
    "dates": "~110 BCE–10 CE",
    "keyIdea": "What is hateful to you, do not do to your neighbor. The rest is commentary.",
    "vector": [
      4,
      7,
      3,
      6,
      6,
      9,
      5,
      3,
      9,
      4,
      9,
      6,
      5,
      4,
      7,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "hillel the elder"
    ]
  },
  {
    "name": "Martin Buber",
    "dates": "1878–1965",
    "keyIdea": "I-Thou versus I-It. All real living is meeting. The eternal Thou meets us in every Thou.",
    "vector": [
      5,
      7,
      2,
      6,
      7,
      7,
      8,
      4,
      9,
      5,
      7,
      7,
      4,
      5,
      8,
      5
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Abraham Heschel",
    "dates": "1907–1972",
    "keyIdea": "Radical amazement. To pray is to praise. The prophets demand justice. God in search of man.",
    "vector": [
      6,
      7,
      3,
      7,
      6,
      8,
      8,
      3,
      8,
      5,
      8,
      7,
      5,
      4,
      9,
      4
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  },
  {
    "name": "Baal Shem Tov",
    "dates": "~1698–1760",
    "keyIdea": "God is everywhere; serve Him with joy. Every Jew has a divine spark. Hasidic devotion through ecstasy.",
    "vector": [
      5,
      8,
      3,
      4,
      7,
      8,
      10,
      2,
      9,
      5,
      8,
      4,
      5,
      5,
      8,
      5
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Cheikh Anta Diop",
    "dates": "1923–1986",
    "keyIdea": "African civilizations are foundational, not derivative. Reclaim history; rebuild the future.",
    "vector": [
      5,
      7,
      7,
      8,
      9,
      7,
      2,
      5,
      9,
      5,
      8,
      7,
      3,
      5,
      6,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Achille Mbembe",
    "dates": "b. 1957",
    "keyIdea": "Necropolitics. The colonial enterprise as the production of death. Becoming Black of the world.",
    "vector": [
      8,
      5,
      7,
      7,
      8,
      3,
      2,
      8,
      7,
      6,
      7,
      8,
      3,
      5,
      5,
      5
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Kwame Anthony Appiah",
    "dates": "b. 1954",
    "keyIdea": "Cosmopolitanism: rooted, partial, but reaching across. Identity is invented but real in its effects.",
    "vector": [
      3,
      7,
      5,
      8,
      8,
      5,
      2,
      6,
      7,
      6,
      8,
      7,
      3,
      5,
      8,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Vine Deloria Jr.",
    "dates": "1933–2005",
    "keyIdea": "God is red. Time is space. Place matters. Indigenous knowledge resists Western abstraction.",
    "vector": [
      6,
      7,
      6,
      5,
      9,
      9,
      7,
      8,
      9,
      5,
      8,
      5,
      3,
      6,
      4,
      3
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": [
      "vine deloria",
      "deloria"
    ]
  },
  {
    "name": "Hobbes",
    "dates": "1588–1679",
    "keyIdea": "Life in the state of nature: nasty, brutish, short. The Leviathan is needed. Power is everything.",
    "vector": [
      7,
      5,
      8,
      9,
      8,
      3,
      0,
      7,
      5,
      5,
      9,
      7,
      3,
      5,
      5,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "thomas hobbes",
      "thomas"
    ]
  },
  {
    "name": "Descartes",
    "dates": "1596–1650",
    "keyIdea": "I think therefore I am. Doubt everything to find what cannot be doubted. Mind and body are distinct.",
    "vector": [
      4,
      5,
      3,
      10,
      3,
      3,
      3,
      8,
      3,
      7,
      5,
      9,
      5,
      2,
      7,
      1
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "rene",
      "rené"
    ]
  },
  {
    "name": "Locke",
    "dates": "1632–1704",
    "keyIdea": "Mind is a blank slate. Government rests on consent. Property comes from labor.",
    "vector": [
      3,
      6,
      5,
      7,
      9,
      4,
      1,
      6,
      5,
      7,
      8,
      6,
      3,
      5,
      7,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "john locke",
      "john"
    ]
  },
  {
    "name": "Berkeley",
    "dates": "1685–1753",
    "keyIdea": "To be is to be perceived. There is no matter without mind. God's perception holds the world steady.",
    "vector": [
      4,
      5,
      2,
      9,
      7,
      6,
      6,
      5,
      5,
      4,
      5,
      9,
      5,
      3,
      7,
      5
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": [
      "george berkeley",
      "george"
    ]
  },
  {
    "name": "Leibniz",
    "dates": "1646–1716",
    "keyIdea": "This is the best of all possible worlds. Monads have no windows. Pre-established harmony.",
    "vector": [
      3,
      7,
      3,
      10,
      5,
      5,
      6,
      3,
      6,
      4,
      6,
      10,
      4,
      3,
      9,
      3
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": [
      "gottfried"
    ]
  },
  {
    "name": "Voltaire",
    "dates": "1694–1778",
    "keyIdea": "Crush the infamy. Defend free speech to the death. Cultivate your garden.",
    "vector": [
      5,
      7,
      6,
      7,
      8,
      2,
      1,
      8,
      6,
      7,
      8,
      6,
      3,
      5,
      7,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "arouet"
    ]
  },
  {
    "name": "Rousseau",
    "dates": "1712–1778",
    "keyIdea": "Man is born free, and everywhere he is in chains. Civilization corrupts. The general will.",
    "vector": [
      6,
      7,
      5,
      5,
      8,
      3,
      5,
      5,
      8,
      8,
      7,
      6,
      4,
      6,
      7,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "jean-jacques",
      "jean jacques"
    ]
  },
  {
    "name": "Francis Bacon",
    "dates": "1561–1626",
    "keyIdea": "Knowledge is power. Idol of the tribe, cave, marketplace, theater. The inductive method.",
    "vector": [
      3,
      6,
      8,
      7,
      10,
      3,
      1,
      7,
      5,
      5,
      8,
      7,
      3,
      5,
      6,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Fichte",
    "dates": "1762–1814",
    "keyIdea": "The I posits itself. The non-I is posited by the I. Moral striving is the ground of being.",
    "vector": [
      4,
      7,
      8,
      9,
      4,
      4,
      6,
      3,
      7,
      9,
      6,
      9,
      5,
      3,
      8,
      4
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Schelling",
    "dates": "1775–1854",
    "keyIdea": "Nature and spirit are one identity. The unconscious ground of being. Mythology as philosophy.",
    "vector": [
      5,
      7,
      5,
      8,
      6,
      5,
      8,
      4,
      6,
      6,
      5,
      9,
      5,
      4,
      8,
      5
    ],
    "archetypeKey": "lighthouse",
    "archetypeName": "The Lighthouse",
    "aliases": []
  },
  {
    "name": "Bergson",
    "dates": "1859–1941",
    "keyIdea": "Duration, not space-time. Élan vital — the creative impulse of life. Intuition over analysis.",
    "vector": [
      4,
      8,
      5,
      6,
      9,
      3,
      7,
      5,
      5,
      6,
      6,
      8,
      3,
      7,
      6,
      6
    ],
    "archetypeKey": "garden",
    "archetypeName": "The Garden",
    "aliases": []
  },
  {
    "name": "Whitehead",
    "dates": "1861–1947",
    "keyIdea": "Reality is process, not substance. Actual occasions of experience. God is not exception but exemplar.",
    "vector": [
      4,
      7,
      4,
      8,
      7,
      5,
      6,
      4,
      7,
      5,
      6,
      9,
      4,
      5,
      8,
      5
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Comte",
    "dates": "1798–1857",
    "keyIdea": "Three stages of human knowledge: theological, metaphysical, positive. Sociology is queen of sciences.",
    "vector": [
      3,
      6,
      7,
      9,
      9,
      4,
      1,
      5,
      7,
      4,
      8,
      8,
      3,
      4,
      8,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Peirce",
    "dates": "1839–1914",
    "keyIdea": "The pragmatic maxim: a concept's meaning is its practical effects. Belief is what we act on.",
    "vector": [
      3,
      6,
      4,
      9,
      9,
      4,
      3,
      5,
      7,
      4,
      7,
      9,
      4,
      4,
      7,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": [
      "charles peirce",
      "c.s."
    ]
  },
  {
    "name": "Camus",
    "dates": "1913–1960",
    "keyIdea": "The struggle itself toward the heights is enough to fill a man's heart. We must imagine Sisyphus happy.",
    "vector": [
      8,
      7,
      4,
      5,
      7,
      2,
      2,
      7,
      5,
      9,
      7,
      5,
      4,
      6,
      5,
      4
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "albert"
    ]
  },
  {
    "name": "Merleau-Ponty",
    "dates": "1908–1961",
    "keyIdea": "The body knows. Perception is not in the head; it is the world meeting flesh.",
    "vector": [
      5,
      7,
      3,
      7,
      9,
      4,
      4,
      5,
      6,
      6,
      6,
      8,
      3,
      9,
      5,
      5
    ],
    "archetypeKey": "garden",
    "archetypeName": "The Garden",
    "aliases": [
      "maurice",
      "merleau ponty"
    ]
  },
  {
    "name": "Karl Jaspers",
    "dates": "1883–1969",
    "keyIdea": "Existence is in limit-situations. The encompassing transcendence. Communicate without conquering.",
    "vector": [
      7,
      7,
      5,
      7,
      6,
      5,
      7,
      6,
      6,
      8,
      6,
      8,
      5,
      4,
      6,
      4
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Paul Ricoeur",
    "dates": "1913–2005",
    "keyIdea": "The narrative self. The hermeneutics of suspicion. Oneself as another.",
    "vector": [
      5,
      6,
      3,
      8,
      7,
      6,
      5,
      5,
      7,
      6,
      7,
      9,
      4,
      5,
      7,
      5
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Hans-Georg Gadamer",
    "dates": "1900–2002",
    "keyIdea": "Understanding happens in the fusion of horizons. Tradition is the live process of meaning.",
    "vector": [
      4,
      6,
      3,
      7,
      7,
      8,
      5,
      4,
      8,
      5,
      7,
      8,
      4,
      4,
      6,
      4
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Habermas",
    "dates": "b. 1929",
    "keyIdea": "Communicative rationality. The ideal speech situation. Public reason as the ground of legitimacy.",
    "vector": [
      4,
      6,
      5,
      9,
      7,
      5,
      1,
      5,
      9,
      5,
      8,
      8,
      3,
      4,
      9,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "jurgen",
      "jürgen"
    ]
  },
  {
    "name": "Adorno",
    "dates": "1903–1969",
    "keyIdea": "The whole is the false. Negative dialectics. The culture industry numbs critique.",
    "vector": [
      8,
      5,
      5,
      8,
      8,
      3,
      1,
      9,
      6,
      6,
      6,
      9,
      5,
      5,
      5,
      4
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": [
      "theodor"
    ]
  },
  {
    "name": "Walter Benjamin",
    "dates": "1892–1940",
    "keyIdea": "The angel of history flies backward. Mechanical reproduction destroys aura. Messianic redemption in fragments.",
    "vector": [
      8,
      6,
      3,
      7,
      7,
      5,
      6,
      7,
      7,
      6,
      6,
      8,
      4,
      5,
      5,
      5
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Deleuze",
    "dates": "1925–1995",
    "keyIdea": "Difference and repetition. Rhizome, not tree. Body without organs. Becomings, not beings.",
    "vector": [
      5,
      8,
      7,
      7,
      8,
      2,
      3,
      7,
      5,
      7,
      6,
      9,
      3,
      7,
      3,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": [
      "gilles"
    ]
  },
  {
    "name": "Derrida",
    "dates": "1930–2004",
    "keyIdea": "Différance. There is nothing outside the text. Deconstruction reveals what cannot be said.",
    "vector": [
      5,
      5,
      4,
      6,
      7,
      4,
      3,
      9,
      6,
      6,
      5,
      9,
      3,
      4,
      3,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": [
      "jacques"
    ]
  },
  {
    "name": "Baudrillard",
    "dates": "1929–2007",
    "keyIdea": "We live in simulation. The real is replaced by the hyperreal. The map precedes the territory.",
    "vector": [
      7,
      5,
      5,
      5,
      8,
      2,
      1,
      9,
      5,
      6,
      5,
      8,
      3,
      5,
      3,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Lyotard",
    "dates": "1924–1998",
    "keyIdea": "Incredulity toward grand narratives. The differend. The sublime breaks the rules.",
    "vector": [
      6,
      5,
      4,
      6,
      8,
      2,
      2,
      9,
      5,
      6,
      5,
      8,
      3,
      5,
      2,
      6
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Marcuse",
    "dates": "1898–1979",
    "keyIdea": "One-dimensional man. The great refusal. Eros against repression.",
    "vector": [
      7,
      6,
      7,
      8,
      7,
      2,
      2,
      7,
      7,
      6,
      7,
      8,
      3,
      6,
      7,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": [
      "herbert"
    ]
  },
  {
    "name": "Bertrand Russell",
    "dates": "1872–1970",
    "keyIdea": "Liberalism, logic, mathematics. The world's problems come more from foolishness than wickedness.",
    "vector": [
      4,
      6,
      5,
      9,
      8,
      3,
      1,
      8,
      5,
      6,
      7,
      9,
      3,
      5,
      6,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Quine",
    "dates": "1908–2000",
    "keyIdea": "The web of belief is revisable everywhere. No fact-value distinction. Naturalized epistemology.",
    "vector": [
      3,
      5,
      3,
      9,
      9,
      3,
      0,
      7,
      4,
      5,
      5,
      10,
      3,
      3,
      5,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": [
      "willard van orman",
      "wvo"
    ]
  },
  {
    "name": "John Searle",
    "dates": "1932–2025",
    "keyIdea": "The Chinese Room. Strong AI is impossible. Speech acts. Social reality from collective intentionality.",
    "vector": [
      3,
      6,
      5,
      9,
      8,
      4,
      1,
      6,
      6,
      5,
      6,
      9,
      3,
      5,
      6,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Daniel Dennett",
    "dates": "1942–2024",
    "keyIdea": "Consciousness is multiple drafts. The self is a center of narrative gravity. Darwin's dangerous idea.",
    "vector": [
      3,
      7,
      5,
      9,
      9,
      2,
      0,
      7,
      5,
      6,
      6,
      9,
      3,
      5,
      6,
      7
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "David Chalmers",
    "dates": "b. 1966",
    "keyIdea": "The hard problem of consciousness. Why is there something it is like to be? Property dualism.",
    "vector": [
      5,
      5,
      3,
      9,
      6,
      2,
      5,
      6,
      5,
      5,
      5,
      10,
      3,
      4,
      5,
      5
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Bernard Williams",
    "dates": "1929–2003",
    "keyIdea": "Moral luck. Internal reasons. Ethics escapes systematic theory.",
    "vector": [
      6,
      6,
      4,
      8,
      8,
      6,
      3,
      6,
      7,
      7,
      8,
      8,
      4,
      5,
      5,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Alasdair MacIntyre",
    "dates": "1929–2025",
    "keyIdea": "After virtue. We need traditions and narratives to ground ethics. The Aristotelian tradition lives.",
    "vector": [
      6,
      6,
      3,
      7,
      6,
      9,
      5,
      5,
      9,
      4,
      8,
      7,
      5,
      4,
      5,
      2
    ],
    "archetypeKey": "hearth",
    "archetypeName": "The Hearth",
    "aliases": []
  },
  {
    "name": "Charles Taylor",
    "dates": "b. 1931",
    "keyIdea": "Sources of the self. Malaises of modernity. Authenticity, recognition, the buffered self.",
    "vector": [
      5,
      7,
      4,
      8,
      7,
      7,
      6,
      4,
      9,
      6,
      7,
      8,
      4,
      4,
      7,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Martha Nussbaum",
    "dates": "b. 1947",
    "keyIdea": "The capabilities approach. Emotions are intelligent. Greek tragedy still teaches us.",
    "vector": [
      5,
      8,
      5,
      8,
      8,
      5,
      3,
      5,
      8,
      6,
      8,
      7,
      4,
      6,
      9,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Michael Sandel",
    "dates": "b. 1953",
    "keyIdea": "Justice cannot be neutral. Markets corrupt the goods they trade. Civic virtue matters.",
    "vector": [
      4,
      7,
      5,
      8,
      7,
      7,
      2,
      5,
      9,
      5,
      8,
      7,
      4,
      4,
      6,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Peter Singer",
    "dates": "b. 1946",
    "keyIdea": "All animals are equal. Effective altruism. Save lives where you can, with what you have.",
    "vector": [
      4,
      7,
      6,
      9,
      8,
      1,
      0,
      6,
      7,
      5,
      8,
      7,
      5,
      4,
      10,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Christine Korsgaard",
    "dates": "b. 1952",
    "keyIdea": "The sources of normativity. Self-constitution. Practical identity grounds reasons.",
    "vector": [
      4,
      5,
      3,
      9,
      5,
      5,
      2,
      5,
      6,
      7,
      6,
      9,
      6,
      3,
      9,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Harry Frankfurt",
    "dates": "1929–2023",
    "keyIdea": "On bullshit. Caring is what makes us persons. Higher-order desires constitute the self.",
    "vector": [
      4,
      6,
      4,
      8,
      6,
      4,
      2,
      5,
      6,
      8,
      6,
      8,
      4,
      4,
      5,
      3
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Richard Rorty",
    "dates": "1931–2007",
    "keyIdea": "Truth is what your contemporaries let you get away with. Solidarity over objectivity. Ironist liberalism.",
    "vector": [
      4,
      7,
      4,
      5,
      8,
      3,
      1,
      9,
      7,
      7,
      7,
      6,
      2,
      5,
      3,
      5
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "George Herbert Mead",
    "dates": "1863–1931",
    "keyIdea": "The self emerges from social interaction. The 'I' and the 'me'. The generalized other.",
    "vector": [
      3,
      6,
      5,
      7,
      9,
      4,
      0,
      5,
      9,
      6,
      8,
      6,
      2,
      5,
      6,
      5
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Judith Butler",
    "dates": "b. 1956",
    "keyIdea": "Gender is performative. The subject is constituted in repetition. Vulnerability is a political resource.",
    "vector": [
      6,
      6,
      6,
      7,
      8,
      2,
      2,
      8,
      7,
      6,
      6,
      9,
      3,
      6,
      4,
      6
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Donna Haraway",
    "dates": "b. 1944",
    "keyIdea": "Cyborg manifesto. Staying with the trouble. Companion species. Knowledge is situated.",
    "vector": [
      5,
      8,
      6,
      7,
      8,
      2,
      4,
      7,
      8,
      6,
      7,
      8,
      3,
      6,
      5,
      6
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Angela Davis",
    "dates": "b. 1944",
    "keyIdea": "Abolition democracy. Prisons cannot be reformed; they must be abolished. Solidarity is action.",
    "vector": [
      6,
      7,
      8,
      7,
      8,
      3,
      1,
      7,
      9,
      6,
      8,
      6,
      3,
      5,
      8,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Gayatri Spivak",
    "dates": "b. 1942",
    "keyIdea": "Can the subaltern speak? Strategic essentialism. Translation as political work.",
    "vector": [
      7,
      5,
      5,
      8,
      7,
      3,
      2,
      9,
      7,
      6,
      6,
      9,
      3,
      4,
      4,
      5
    ],
    "archetypeKey": "touchstone",
    "archetypeName": "The Touchstone",
    "aliases": []
  },
  {
    "name": "Sylvia Wynter",
    "dates": "b. 1928",
    "keyIdea": "We must unsettle the colonial Man. Rewrite the human. The science of being hybridly human.",
    "vector": [
      6,
      7,
      6,
      8,
      7,
      4,
      3,
      7,
      8,
      5,
      7,
      9,
      3,
      5,
      6,
      3
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Cornel West",
    "dates": "b. 1953",
    "keyIdea": "Prophetic pragmatism. Justice is what love looks like in public. Black self-love and political courage.",
    "vector": [
      6,
      8,
      7,
      7,
      8,
      7,
      6,
      5,
      9,
      6,
      8,
      6,
      4,
      5,
      8,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Stuart Hall",
    "dates": "1932–2014",
    "keyIdea": "Cultural studies. Encoding and decoding. Identity as positions we are summoned to inhabit.",
    "vector": [
      5,
      6,
      6,
      7,
      8,
      3,
      1,
      7,
      9,
      5,
      7,
      8,
      3,
      5,
      5,
      4
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "D.T. Suzuki",
    "dates": "1870–1966",
    "keyIdea": "Zen as direct experience beyond intellect. Satori cannot be taught, only pointed to.",
    "vector": [
      5,
      7,
      3,
      4,
      8,
      6,
      9,
      5,
      6,
      6,
      8,
      5,
      6,
      4,
      7,
      9
    ],
    "archetypeKey": "threshold",
    "archetypeName": "The Threshold",
    "aliases": []
  },
  {
    "name": "Carl Jung",
    "dates": "1875–1961",
    "keyIdea": "The collective unconscious. Archetypes. Individuation through facing the shadow.",
    "vector": [
      6,
      7,
      4,
      5,
      7,
      6,
      8,
      5,
      6,
      7,
      7,
      8,
      4,
      5,
      6,
      5
    ],
    "archetypeKey": "pilgrim",
    "archetypeName": "The Pilgrim",
    "aliases": []
  },
  {
    "name": "Mary Astell",
    "dates": "1666–1731",
    "keyIdea": "Reason is not gendered. Education for women. Friendship as the truest love.",
    "vector": [
      4,
      6,
      5,
      9,
      6,
      6,
      4,
      5,
      6,
      7,
      7,
      7,
      5,
      4,
      8,
      2
    ],
    "archetypeKey": "cartographer",
    "archetypeName": "The Cartographer",
    "aliases": []
  },
  {
    "name": "Sojourner Truth",
    "dates": "~1797–1883",
    "keyIdea": "Ain't I a woman? The truth burns through silence. Faith and freedom inseparable.",
    "vector": [
      7,
      8,
      7,
      5,
      9,
      5,
      6,
      5,
      8,
      9,
      8,
      3,
      4,
      6,
      8,
      2
    ],
    "archetypeKey": "forge",
    "archetypeName": "The Forge",
    "aliases": []
  },
  {
    "name": "Albert Schweitzer",
    "dates": "1875–1965",
    "keyIdea": "Reverence for life. Ethics is responsibility without limit. Theology, music, medicine, mission.",
    "vector": [
      6,
      8,
      4,
      7,
      7,
      5,
      5,
      4,
      9,
      6,
      9,
      5,
      6,
      4,
      9,
      2
    ],
    "archetypeKey": "keel",
    "archetypeName": "The Keel",
    "aliases": []
  }
];

export function matchesPhilosopherSearch(p: PhilosopherEntry, q: string): boolean {
  const needle = q.toLowerCase().trim();
  if (!needle) return true;
  if (p.name.toLowerCase().includes(needle)) return true;
  if ((p.keyIdea || '').toLowerCase().includes(needle)) return true;
  for (const a of p.aliases) {
    if (a.toLowerCase().includes(needle)) return true;
  }
  return false;
}

// URL slug for a philosopher name. Diacritic-stripped, kebab-cased,
// alpha-numeric only. Examples: "Plato" → "plato", "Søren Kierkegaard"
// → "soren-kierkegaard", "Ibn Sīnā (Avicenna)" → "ibn-sina-avicenna".
// Stable identifier suitable for /philosopher/[slug] routes.
export function philosopherSlug(name: string): string {
  return name
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')   // strip diacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')        // collapse to hyphens
    .replace(/^-+|-+$/g, '');           // trim hyphens
}

// All slugs (for generateStaticParams + sitemap).
export function philosopherSlugs(): string[] {
  return PHILOSOPHERS.map(p => philosopherSlug(p.name));
}

// Lookup by slug. Returns undefined if no match. Built once + cached
// because /philosopher/[slug] hits this on every static-render.
let _slugIndex: Map<string, PhilosopherEntry> | null = null;
function buildSlugIndex(): Map<string, PhilosopherEntry> {
  if (_slugIndex) return _slugIndex;
  const m = new Map<string, PhilosopherEntry>();
  for (const p of PHILOSOPHERS) {
    m.set(philosopherSlug(p.name), p);
  }
  _slugIndex = m;
  return m;
}
export function getPhilosopherBySlug(slug: string): PhilosopherEntry | undefined {
  return buildSlugIndex().get(slug);
}

// Cosine similarity between two equal-length vectors. Used to find
// philosophers nearest to a given philosopher in the constellation.
function cosineSim(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  const len = Math.min(a.length, b.length);
  for (let i = 0; i < len; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  if (na === 0 || nb === 0) return 0;
  return dot / Math.sqrt(na * nb);
}

// Top-N other philosophers closest to the given one in vector space.
// Used on the /philosopher/[slug] page to surface kindred minds —
// purely vector-based, doesn't require any human-curated relationships.
export function nearestPhilosophers(target: PhilosopherEntry, n = 6): PhilosopherEntry[] {
  return PHILOSOPHERS
    .filter(p => p.name !== target.name)
    .map(p => ({ p, sim: cosineSim(target.vector, p.vector) }))
    .sort((a, b) => b.sim - a.sim)
    .slice(0, n)
    .map(x => x.p);
}

// Top dimensions the philosopher leans into — used to render a small
// "what makes them them" snapshot on their detail page.
export function topDimensions(p: PhilosopherEntry, n = 4): { idx: number; value: number }[] {
  return p.vector
    .map((value, idx) => ({ idx, value }))
    .sort((a, b) => b.value - a.value)
    .slice(0, n);
}
